server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/LeTanHai/Spring-Boot-Microservice.git
                    basedir: target/configs
        lable: master          
    application:
        name: config-server